version: '3.8'

services:
  payment-db:
    image: mongo:latest
    container_name: payment-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: payment-service
    volumes:
      - payment-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - payment-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/payment-service --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://root:password@payment-db:27017/payment-service?authSource=admin
      - NODE_ENV=production
      - SERVICE_NAME=payment-service-${HOSTNAME}
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - payment-db
    networks:
      - payment-network
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: payment-nginx
    restart: always
    ports:
      - "8080:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-service
    networks:
      - payment-network

networks:
  payment-network:
    driver: bridge

volumes:
  payment-data:
    name: payment-data