version: '3.8'

services:
  review-api-1:
    build: .
    container_name: review-api-1
    environment:
      - PORT=5000
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-net

  review-api-2:
    build: .
    container_name: review-api-2
    environment:
      - PORT=5000
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - review-api-1
      - review-api-2
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
