services:
  booking-service:
    container_name: booking-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DATABASE_URI=mongodb+srv://travique-booking-service:BookingService1234@bookingservicecluster.nx0eqky.mongodb.net/?retryWrites=true&w=majority&appName=BookingServiceCluster
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - travique-network

networks:
  travique-network:
    name: travique-network