version: "3.8"

services:
  booking-service:
    build: .
    env_file: .env
    networks:
      - travique-network
    depends_on:
      - mongodb
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - travique-network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - booking-service
    networks:
      - travique-network

volumes:
  mongo-data:

networks:
  travique-network:
    external: true
