version: "3.8"

services:
  booking-service:
    build: .
    env_file: .env
    networks:
      - travique-network
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - travique-network
    environment: #
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: booking-db 
    healthcheck: 
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  booking-nginx:
    image: nginx
    container_name: booking-nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - booking-service
    networks:
      - travique-network

volumes:
  mongo-data:

networks:
  travique-network:
    external: true
