version: "3.8"

services:
  booking-service:
    build: .
    env_file: .env
    networks:
      - travique-network
    depends_on:
      - mongo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: booking-db
    volumes:
      - mongo-data:/data/db
    networks:
      - travique-network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - booking-service
    networks:
      - travique-network

volumes:
  mongo-data:

networks:
  travique-network:
    name: travique-network
