services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend-app
    restart: always
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - travique_network

networks:
  travique_network: